services:
  yotoshare:
    image: ghcr.io/bubu31/yotoshare:latest
    container_name: yotoshare
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yotoshare.rule=Host(`yoto.busolin.fr`)"
      - "traefik.http.routers.yotoshare.entrypoints=websecure"
      - "traefik.http.routers.yotoshare.tls.certresolver=letsencrypt"
      - "traefik.http.services.yotoshare.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
